# Generated by Django 3.2.9 on 2021-11-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='date_time',
        ),
    ]
