# Generated by Django 3.2.8 on 2021-11-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
