# Generated by Django 3.2.8 on 2021-11-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20211104_1704'),
        ('hospital', '0003_remove_patient_password'),
    ]

    operations = [
    ]
