# Generated by Django 3.2.9 on 2021-11-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
