# Generated by Django 3.2.9 on 2021-11-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_bill_room_roominstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_day',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='roominstance',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
