# Generated by Django 3.2.9 on 2021-11-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20211108_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominstance',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='roominstance',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomInstance',
        ),
    ]
