# Generated by Django 3.2.9 on 2021-11-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20211108_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='medicine_fee',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='other_fee',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='room_fee',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='service_fee',
        ),
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='items',
            field=models.ManyToManyField(to='hospital.BillItem'),
        ),
    ]
