# Generated by Django 3.2.9 on 2021-11-09 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_bill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='items',
        ),
        migrations.CreateModel(
            name='Bill_BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.bill')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.billitem')),
            ],
        ),
    ]
