# Generated by Django 3.2.9 on 2021-11-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auto_20211109_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill_BillItem',
            new_name='BillItemMap',
        ),
        migrations.RenameModel(
            old_name='BillItem',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='name',
        ),
    ]
