# Generated by Django 3.2.9 on 2021-11-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_bed_bedinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedinstance',
            options={'ordering': ['-admitted_on']},
        ),
        migrations.AddField(
            model_name='patient',
            name='admitted',
            field=models.BooleanField(default=False),
        ),
    ]
